/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function setCredential(serviceName: string, authorName: string, password: string): void
export declare function getCredential(serviceName: string, authorName: string): string
export declare function removeTemplateEnginesSyntax(text: string): string
export declare function formatPath(path: string, contentType: string): string
export declare function shouldSkipPaths(path: string, skipPaths: Array<string>): boolean
export declare function externalLink(data: string, baseUrl: string): string
export declare function generateRobots(noindex: boolean | undefined | null, contentType: string): string
export declare function renderMarkdown(input: string): string
export declare function logInfo(message: string): void
export declare function logWarn(message: string): void
export declare function logError(message: string): void
export declare function logDebug(message: string): void
export declare function setLogLevel(level: string): void
export declare function getLogLevel(): string
export declare function isValidImage(source: string): boolean
