/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function setCredential(serviceName: string, authorName: string, password: string): void
export declare function getCredential(serviceName: string, authorName: string): string
