/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function externalLink(data: string, baseUrl: string): string

export declare function formatPath(path: string, contentType: string): string

export declare function generateRobots(noindex: boolean | undefined | null, contentType: string): string

export declare function getCredential(serviceName: string, authorName: string): string

export declare function getLogLevel(): string

export declare function httpDelete(baseUrl: string, path: string, token?: string | undefined | null): Promise<string>

export declare function httpGet(baseUrl: string, path: string, token?: string | undefined | null): Promise<string>

export declare function httpPost(baseUrl: string, path: string, data: string, token?: string | undefined | null): Promise<string>

export declare function isValidImage(source: string): boolean

export declare function logDebug(message: string): void

export declare function logError(message: string): void

export declare function logInfo(message: string): void

export declare function logWarn(message: string): void

export declare function removeTemplateEnginesSyntax(text: string): string

export declare function renderMarkdown(input: string): string

export declare function setCredential(serviceName: string, authorName: string, password: string): void

export declare function setLogLevel(level: string): void

export declare function shouldSkipPaths(path: string, skipPaths: Array<string>): boolean
